/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBackOffTrigger struct {
	DeferralPercentage int64 `json:"deferralPercentage,omitempty"`
	DurationInMinutes int64 `json:"durationInMinutes,omitempty"`
	HardBouncePercentage int64 `json:"hardBouncePercentage,omitempty"`
	MinimumAttempts int64 `json:"minimumAttempts,omitempty"`
}
