/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsIp struct {
	AolSettings string `json:"aolSettings,omitempty"`
	AutoWarmupEnabled bool `json:"autoWarmupEnabled,omitempty"`
	AutoWarmupStage int64 `json:"autoWarmupStage,omitempty"`
	ComcastSettings string `json:"comcastSettings,omitempty"`
	Created int64 `json:"created,omitempty"`
	DefaultSettings string `json:"defaultSettings,omitempty"`
	GmailSettings string `json:"gmailSettings,omitempty"`
	GmxSettings string `json:"gmxSettings,omitempty"`
	IcloudSettings string `json:"icloudSettings,omitempty"`
	Id int64 `json:"id,omitempty"`
	MailruSettings string `json:"mailruSettings,omitempty"`
	MicrosoftSettings string `json:"microsoftSettings,omitempty"`
	PublicIP string `json:"publicIP,omitempty"`
	QqSettings string `json:"qqSettings,omitempty"`
	ReverseDNSHostname string `json:"reverseDNSHostname,omitempty"`
	SystemDomain *ModelsSystemDomain `json:"systemDomain,omitempty"`
	Type_ *ModelsIpType `json:"type,omitempty"`
	YahooSettings string `json:"yahooSettings,omitempty"`
	YandexSettings string `json:"yandexSettings,omitempty"`
	ZohoSettings string `json:"zohoSettings,omitempty"`
}
