/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSystemDomain struct {
	Created int64 `json:"created,omitempty"`
	Dkim *ModelsSystemDnsRecord `json:"dkim,omitempty"`
	DkimConfig string `json:"dkimConfig,omitempty"`
	DkimVerified bool `json:"dkimVerified,omitempty"`
	Id int64 `json:"id,omitempty"`
	MailboxVerified bool `json:"mailboxVerified,omitempty"`
	Name string `json:"name,omitempty"`
	Spf *ModelsSystemDnsRecord `json:"spf,omitempty"`
	SpfVerified bool `json:"spfVerified,omitempty"`
	Track *ModelsSystemDnsRecord `json:"track,omitempty"`
	TrackVerified bool `json:"trackVerified,omitempty"`
}
