/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsAipStat struct {
	Ipid int64 `json:"ipid,omitempty"`
	PublicIP string `json:"publicIP,omitempty"`
	Stat *ModelsIpStat `json:"stat,omitempty"`
}
