/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsIip struct {
	BackOffConfiguration *ModelsBackOffConfiguration `json:"backOffConfiguration,omitempty"`
	BackOffTrigger *ModelsBackOffTrigger `json:"backOffTrigger,omitempty"`
	MaxConcurrentConnections int64 `json:"maxConcurrentConnections,omitempty"`
	MaxSendPerDay int64 `json:"maxSendPerDay,omitempty"`
	MaxSendPerHour int64 `json:"maxSendPerHour,omitempty"`
	MaxSendPerMinute int64 `json:"maxSendPerMinute,omitempty"`
	Name string `json:"name,omitempty"`
}
