/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsAuthInfo struct {
	Accounts []ModelsAccount `json:"Accounts,omitempty"`
	Member *ModelsMember `json:"Member,omitempty"`
}
