/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEmailMessage struct {
	AmpBody string `json:"ampBody,omitempty"`
	From *ModelsFrom `json:"from,omitempty"`
	Groups *interface{} `json:"groups,omitempty"`
	Headers *interface{} `json:"headers,omitempty"`
	HtmlBody string `json:"htmlBody,omitempty"`
	Ippool string `json:"ippool,omitempty"`
	PreText string `json:"preText,omitempty"`
	ReplyTo *ModelsReplyTo `json:"replyTo,omitempty"`
	Subject string `json:"subject,omitempty"`
	TextBody string `json:"textBody,omitempty"`
	To []ModelsTo `json:"to,omitempty"`
	TrackClicks bool `json:"trackClicks,omitempty"`
	TrackOpens bool `json:"trackOpens,omitempty"`
}
