/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsRipStat struct {
	Date string `json:"date,omitempty"`
	Stat *ModelsIpStat `json:"stat,omitempty"`
}
