/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBackOffConfiguration struct {
	ConcurrentConnections int64 `json:"concurrentConnections,omitempty"`
	ConcurrentConnectionsType *ModelsBackOffDecreaseType `json:"concurrentConnectionsType,omitempty"`
	SendPerDay int64 `json:"sendPerDay,omitempty"`
	SendPerDayType *ModelsBackOffDecreaseType `json:"sendPerDayType,omitempty"`
	SendPerHour int64 `json:"sendPerHour,omitempty"`
	SendPerHourType *ModelsBackOffDecreaseType `json:"sendPerHourType,omitempty"`
	SendPerMinute int64 `json:"sendPerMinute,omitempty"`
	SendPerMinuteType *ModelsBackOffDecreaseType `json:"sendPerMinuteType,omitempty"`
}
