/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSipStat struct {
	Name string `json:"name,omitempty"`
	Sid int64 `json:"sid,omitempty"`
	Stat *ModelsIpStat `json:"stat,omitempty"`
}
