/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEventMetadata struct {
	ClickedURL string `json:"clickedURL,omitempty"`
	Device *UaparserDevice `json:"device,omitempty"`
	Geo *ModelsCity `json:"geo,omitempty"`
	Os *UaparserOs `json:"os,omitempty"`
	SmtpCode int64 `json:"smtpCode,omitempty"`
	SmtpDescription string `json:"smtpDescription,omitempty"`
	UserAgent *UaparserUserAgent `json:"userAgent,omitempty"`
}
