/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsCity struct {
	CityID int32 `json:"cityID,omitempty"`
	ContinentCode string `json:"continentCode,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
	TimeZone string `json:"timeZone,omitempty"`
}
