/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UaparserUserAgent struct {
	Family string `json:"Family,omitempty"`
	Major string `json:"Major,omitempty"`
	Minor string `json:"Minor,omitempty"`
	Patch string `json:"Patch,omitempty"`
}
