/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsIpPool struct {
	Created int64 `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	Ips []ModelsIp `json:"ips,omitempty"`
	Name string `json:"name,omitempty"`
	RoutingMetaData string `json:"routingMetaData,omitempty"`
	RoutingStrategy int64 `json:"routingStrategy,omitempty"`
	Type_ *ModelsIpPoolType `json:"type,omitempty"`
}
