/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsRSuppression struct {
	HardBounce []ModelsSuppressionEmail `json:"hardBounce,omitempty"`
	Manual []ModelsSuppressionEmail `json:"manual,omitempty"`
	SpamComplaint []ModelsSuppressionEmail `json:"spamComplaint,omitempty"`
	Unsubscribe []ModelsSuppressionEmail `json:"unsubscribe,omitempty"`
}
