/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsESender struct {
	Domain string `json:"domain,omitempty"`
	FromEmail string `json:"fromEmail,omitempty"`
	Name string `json:"name,omitempty"`
	ReplyToEmail string `json:"replyToEmail,omitempty"`
}
