/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsQEvent struct {
	AccountID int64 `json:"accountID,omitempty"`
	EventID string `json:"eventID,omitempty"`
	EventMetadata *ModelsEventMetadata `json:"eventMetadata,omitempty"`
	From string `json:"from,omitempty"`
	Groups *interface{} `json:"groups,omitempty"`
	IpID int64 `json:"ipID,omitempty"`
	MessageID string `json:"messageID,omitempty"`
	MessageType string `json:"messageType,omitempty"`
	SubAccountID int64 `json:"subAccountID,omitempty"`
	SubmittedAt int64 `json:"submittedAt,omitempty"`
	To string `json:"to,omitempty"`
	Type_ int64 `json:"type,omitempty"`
}
