/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsIntegrationSettings struct {
	AutoEnableMonitoring bool `json:"autoEnableMonitoring,omitempty"`
	EmailTo []string `json:"emailTo,omitempty"`
	Frequency *ModelsFrequencyType `json:"frequency,omitempty"`
	ReceiveReports bool `json:"receiveReports,omitempty"`
}
