/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsDnsRecord struct {
	Host string `json:"host,omitempty"`
	TextValue string `json:"textValue,omitempty"`
	Type_ string `json:"type,omitempty"`
}
