/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsLabel struct {
	Color string `json:"color,omitempty"`
	Created int64 `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
