/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSuppression struct {
	Created int64 `json:"created,omitempty"`
	Email string `json:"email,omitempty"`
	Id int64 `json:"id,omitempty"`
	Reason *ModelsSuppressionReason `json:"reason,omitempty"`
	SmtpError string `json:"smtp_error,omitempty"`
}
